### ISSUE TITLE
Keep `PowerDensity` and `EnergyDensity` instead of `Irradiation` and `Irradiance`

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemUtils#244]
As these are more generic and can and their units e.g. Watt/m^2 can and will be used in other contexts. For example for average power of a household in Osmogrid.

**Comment by t-ober** [comment]
Got renamed to Irradiance for PVs - make irradiance "sub interface" of power density?

**Comment by johanneshiry** [comment]
Does not make sense as described here -> https://github.com/ie3-institute/PowerSystemUtils/pull/246#pullrequestreview-951229131

**Comment by johanneshiry** [comment]
Regarding your comment (here)[https://github.com/ie3-institute/PowerSystemUtils/pull/246#issuecomment-1107893133]: 

First of all, watt per squaremeter and energy per squaremeter in literature is always considered to represent the power or energy _received_ by a surface and _not_ installed on a surface. I think that's the main difference between what is represented by the SI unit and what is _required_ in OSMoGrid households. From this perspective having a general, more generic unit called `PowerDensity` or `EnergyDensity` may not make sense at all, as these names are already taken by the specification. 

So how to solve the OSMoGrid 'issue' then? I would propose to have an OSMoGrid-specific unit inside OSMoGrid with a proper description _why_ this is required and that is not a _real_ unit or SI unit, but more an artificial understanding of power per squaremeter in OSMoGrid. I think this would be the cleanest way to address this issue in order to avoid future confusion. 

Side-node: we had a lot of struggles in the past with exactly this issue, which actually caused the renaming of PowerDensity and EnergyDensity to the actual SI unit names we _wanted_ to have. 

An approach inside OSMoGrid to handle this may look like the following:

```scala 

/**
 * Todo add documentation WHY this is actually required and that this is NOT an SI unit and therefore should NOT
 * leave the context/scope of OSMoGrid
 */
sealed trait InstalledPowerPerArea extends ComparableQuantity[InstalledPowerPerArea]

case object OSMoGridUnits extends Units {

  // if you still want to go with PSUs you may use approach 1, otherwise approach 2 IMHO might be suitable as well

  // approach 1
  val HOUSEHOLD_POWER_DENSITY_V1: measure.Unit[InstalledPowerPerArea] =
    PowerSystemUnits.WATT_PER_SQUAREMETRE.asType(classOf[InstalledPowerPerArea])

  // approach 2
  val HOUSEHOLD_POWER_DENSITY_V2: measure.Unit[InstalledPowerPerArea] =
    new ProductUnit[InstalledPowerPerArea](PowerSystemUnits.KILOWATT.divide(Units.SQUARE_METRE));


  // always required is the label registration for the units
  private val unitFormatInstance = SimpleUnitFormat.getInstance()
  private val REGISTERED_LABELS = Set(unitFormatInstance.label(HOUSEHOLD_POWER_DENSITY_V1, "W/m²"),
    unitFormatInstance.label(HOUSEHOLD_POWER_DENSITY_V2, "W/m²"),
  )

}

```

**Comment by t-ober** [comment]
First of all thanks for the elaborate feedback and the solution proposal - this will be missed! 😢 

:joy: I like the third one!
Yes you are right. I agree. Although to be super specific irradiance is not a SI-Unit per se but a derived one that has its own name, it is part of the official SI-Unit system so we definitely should keep it. Also like the differentiation between installed power and received power per surface area these are in fact different things and should be considered as such.

Will go with one of the your approaches and implement that case within `OsmoGrid`.
Thanks 🙂
